#!/bin/zsh

printf "\033c"

echo "\033[1;31m
  ░█████╗░░█████╗░░██████╗░██████╗░
  ██╔══██╗██╔══██╗██╔════╝██╔════╝░
  ███████║██║░░╚═╝╚█████╗░██║░░██╗░
  ██╔══██║██║░░██╗░╚═══██╗██║░░╚██╗
  ██║░░██║╚█████╔╝██████╔╝╚██████╔╝
  ╚═╝░░╚═╝░╚════╝░╚═════╝░░╚═════╝░\033[00m"

echo ""
echo "      Internal Testing Machine"
echo ""

#Last Logins
USER=$(last -2 -w | head -2 | tail -1 | cut -d ' ' -f '1')
IP=$(last -2 -w | head -2 | tail -1 | cut -d ' ' -f '16')
HOSTNAME=$(last -d -a | head -2 | tail -1 | cut -d ' ' -f '27')
DATE=$(last -2 -w | head -2 | tail -1 | cut -d ' ' -f '30,31,32,33')

#echo "User: $USER"
#echo "IP: $IP"
#echo "Host: $HOSTNAME"
#echo "DAte: $DATE"

echo "Last Login \033[1;31m$USER\033[00m from \033[1;31m$IP\033[00m (\033[1;31m$HOSTNAME\033[00m) on $DATE EST"
echo ""
